### ISSUE TITLE
Don't inherited from the AndroidArtifacts extension

### ISSUE THREAD

**Issue by StefMa** [StefMa/ArtifactoryPublish#31]
Do not extend the AndroidArtifacts extension but create our own.
The user have to setup two extensions.

**Comment by DevAhamed** [comment]
Any updates on this issue? I want to use both [ArtifactoryPublish](https://github.com/StefMa/ArtifactoryPublish/) and [bintray-release](https://github.com/StefMa/bintray-release) in the same project. 

Or should i just use ArtifactoryPublish to publish into artifactory and move the releae into bintray?

**Comment by StefMa** [comment]
Hey @DevAhamed 

that have nothing to do with this issue.
But thanks for the hint.
I created a new issue for it [here](https://github.com/StefMa/ArtifactoryPublish/issues/32) and [here](https://github.com/StefMa/bintray-release/issues/5).
